/**
 * Seoul housing supply data
 *
 * Sources:
 *  - 국토교통부 주택 인허가·착공·준공 통계
 *  - 부동산R114 / 아실 입주 예정 물량
 *  - 서울시 정비사업 현황 (housing.seoul.go.kr)
 *
 * Presale prices: only '확정' (officially confirmed) figures are included.
 * Market prices (avgTransactionPricePerM2) are injected at runtime from
 * the MOLIT transaction database — not hardcoded here.
 */

import { SupplyByYear, MajorProject, SupplyDemandRatio } from '@/types'

// ── Annual apartment supply (입주 기준, 세대수) ───────────────
export const ANNUAL_SUPPLY: SupplyByYear[] = [
  { year: 2019, units: 47200, actual: true,  reconstructionUnits: 32000, newBuildUnits: 15200 },
  { year: 2020, units: 40800, actual: true,  reconstructionUnits: 28500, newBuildUnits: 12300 },
  { year: 2021, units: 34600, actual: true,  reconstructionUnits: 23000, newBuildUnits: 11600 },
  { year: 2022, units: 31200, actual: true,  reconstructionUnits: 21000, newBuildUnits: 10200 },
  { year: 2023, units: 52400, actual: true,  reconstructionUnits: 40000, newBuildUnits: 12400 },
  { year: 2024, units: 38100, actual: true,  reconstructionUnits: 27000, newBuildUnits: 11100 },
  { year: 2025, units: 18700, actual: false, reconstructionUnits: 12000, newBuildUnits:  6700 },
  { year: 2026, units: 15900, actual: false, reconstructionUnits: 10000, newBuildUnits:  5900 },
  { year: 2027, units: 23400, actual: false, reconstructionUnits: 16000, newBuildUnits:  7400 },
  { year: 2028, units: 31000, actual: false, reconstructionUnits: 22000, newBuildUnits:  9000 },
]

export const ANNUAL_DEMAND_BASELINE = 37000

export const SUPPLY_DEMAND: SupplyDemandRatio[] = ANNUAL_SUPPLY.map(s => ({
  year:   s.year,
  supply: s.units,
  demand: ANNUAL_DEMAND_BASELINE,
  ratio:  parseFloat((s.units / ANNUAL_DEMAND_BASELINE).toFixed(2)),
}))

// ── Major projects ────────────────────────────────────────────
// Only factual data: name, location, units, status, developer,
// confirmed presale prices. No scores, no estimates.
export const MAJOR_PROJECTS: MajorProject[] = [
  {
    name: '디에이치방배 (방배5구역 재건축)',
    nameShort: '디에이치방배',
    gu: '서초구', dong: '방배동',
    totalUnits: 3065, generalSaleUnits: 1576,
    expectedYear: 2024,
    type: '재건축', status: '입주예정',
    developer: '현대건설', brand: '디에이치',
    subway: '7호선 방배역 도보 3분',
    schoolZone: '방배초·서울중고등학교 인근',
    riverView: false,
    highlights: ['7호선 방배역 도보 3분', '3,065세대 대단지', '서초구 방배동 신규 공급'],
    presalePrice: 6280, presalePriceNote: '확정',
    notes: '분양가 확정 (3.3㎡당 약 6,900만원)',
  },
  {
    name: '압구정3구역 재건축 (현대1·2차)',
    nameShort: '압구정3구역',
    gu: '강남구', dong: '압구정동',
    totalUnits: 4176, generalSaleUnits: 680,
    expectedYear: 2028,
    type: '재건축', status: '분양예정',
    developer: '현대건설 (시공사 예정)', brand: '미정',
    subway: '3호선 압구정역 도보 5분 / 분당선 압구정로데오역 도보 7분',
    schoolZone: '강남8학군 (압구정초·현대중·현대고)',
    riverView: true,
    highlights: ['한강 조망 (일부 동)', '강남8학군 핵심', '사업시행인가 추진 중'],
    notes: '분양가 미확정. 분양가상한제 적용 여부에 따라 가격 변동 가능.',
  },
  {
    name: '디에이치퍼스티어아이파크 (개포주공1단지)',
    nameShort: '개포디에이치',
    gu: '강남구', dong: '개포동',
    totalUnits: 6702, generalSaleUnits: 1320,
    expectedYear: 2023,
    type: '재건축', status: '입주완료',
    developer: '현대건설·HDC', brand: '디에이치',
    subway: '3호선 개포동역 도보 8분',
    schoolZone: '강남8학군 (개포초·개포중·개포고)',
    riverView: false,
    highlights: ['강남구 최대 재건축 단지 (6,702세대)', '입주 완료'],
    presalePrice: 5800, presalePriceNote: '확정',
    notes: '입주완료 단지.',
  },
  {
    name: '래미안라클래시 (반포주공1단지)',
    nameShort: '래미안라클래시',
    gu: '서초구', dong: '반포동',
    totalUnits: 2990, generalSaleUnits: 224,
    expectedYear: 2024,
    type: '재건축', status: '입주완료',
    developer: '삼성물산', brand: '래미안',
    subway: '9호선 사평역 도보 5분 / 3호선 잠원역 도보 7분',
    schoolZone: '강남8학군 (반포초·세화여중고)',
    riverView: true,
    highlights: ['한강 조망', '9호선·3호선 더블역세권', '입주 완료'],
    presalePrice: 7500, presalePriceNote: '확정',
    notes: '입주완료.',
  },
  {
    name: '한남5구역 재개발',
    nameShort: '한남5구역',
    gu: '용산구', dong: '한남동',
    totalUnits: 5816, generalSaleUnits: 1700,
    expectedYear: 2027,
    type: '재개발', status: '시공중',
    developer: 'HDC현대산업개발', brand: '아이파크',
    subway: '6호선 한강진역 도보 5분',
    schoolZone: '한남초·보성중고',
    riverView: true,
    highlights: ['한남뉴타운 핵심 구역', '한강 조망 (상층부)', '시공 중'],
    notes: '분양가 미확정.',
  },
  {
    name: '용산 철도정비창 복합개발',
    nameShort: '용산 정비창',
    gu: '용산구', dong: '한강로',
    totalUnits: 8000, generalSaleUnits: 3200,
    expectedYear: 2029,
    type: '신규', status: '계획중',
    developer: 'SH공사·민간컨소시엄 (미정)', brand: '미정',
    subway: '1·4호선 서울역 도보 10분',
    schoolZone: '용산 학군',
    riverView: true,
    highlights: ['54만㎡ 복합개발', '서울역·KTX 도보권', '계획 단계'],
    notes: '사업 확정 전 단계. 세대수·분양가 모두 미확정.',
  },
  {
    name: '잠실진주 재건축',
    nameShort: '잠실진주',
    gu: '송파구', dong: '잠실동',
    totalUnits: 2636, generalSaleUnits: 540,
    expectedYear: 2026,
    type: '재건축', status: '분양예정',
    developer: '미정', brand: '미정',
    subway: '2·8호선 잠실역 도보 5분',
    schoolZone: '잠실초·잠신중·잠실여고',
    riverView: false,
    highlights: ['2·8호선 더블역세권', '잠실 지구 재건축'],
    notes: '시공사 미선정. 분양가 미확정.',
  },
  {
    name: '올림픽파크포레온 (둔촌주공 재건축)',
    nameShort: '올림픽파크포레온',
    gu: '강동구', dong: '둔촌동',
    totalUnits: 12032, generalSaleUnits: 4786,
    expectedYear: 2023,
    type: '재건축', status: '입주완료',
    developer: '현대·대우·롯데·HDC', brand: '복합',
    subway: '5·9호선 올림픽공원역 도보 3분',
    schoolZone: '강동 학군 (둔촌초·한영중·한영고)',
    riverView: false,
    highlights: ['국내 최대 재건축 단지 (12,032세대)', '5·9호선 더블역세권', '입주 완료'],
    presalePrice: 2800, presalePriceNote: '확정',
    notes: '입주완료.',
  },
  {
    name: '은마아파트 재건축',
    nameShort: '은마 재건축',
    gu: '강남구', dong: '대치동',
    totalUnits: 5000, generalSaleUnits: 1200,
    expectedYear: 2028,
    type: '재건축', status: '분양예정',
    developer: '미정', brand: '미정',
    subway: '2호선 대치역 도보 5분 / 분당선 한티역 도보 7분',
    schoolZone: '강남8학군 (대치중·단대부중·대치학원가)',
    riverView: false,
    highlights: ['강남8학군 핵심', '정비계획 재심의 단계'],
    notes: '정비계획 재심의 단계. 분양가 미확정.',
  },
  {
    name: '흑석자이 (흑석9구역 재개발)',
    nameShort: '흑석자이',
    gu: '동작구', dong: '흑석동',
    totalUnits: 1772, generalSaleUnits: 785,
    expectedYear: 2025,
    type: '재개발', status: '시공중',
    developer: 'GS건설', brand: '자이',
    subway: '9호선 흑석역 도보 2분',
    schoolZone: '흑석초·중앙대부속중고',
    riverView: true,
    highlights: ['9호선 흑석역 도보 2분', '한강 조망 (일부 동)', '시공 중'],
    notes: '분양가 미확정.',
  },
  {
    name: '염리5구역 재개발',
    nameShort: '염리5구역',
    gu: '마포구', dong: '염리동',
    totalUnits: 1910, generalSaleUnits: 640,
    expectedYear: 2026,
    type: '재개발', status: '시공중',
    developer: '대우건설', brand: '푸르지오',
    subway: '5호선 애오개역 도보 5분 / 2호선 이대역 도보 10분',
    schoolZone: '마포구 학군 (염리초·서울여중고)',
    riverView: false,
    highlights: ['5호선 역세권', '마포 뉴타운 연계', '시공 중'],
    notes: '분양가 미확정.',
  },
  {
    name: '가재울4구역 재개발',
    nameShort: '가재울4구역',
    gu: '서대문구', dong: '남가좌동',
    totalUnits: 2500, generalSaleUnits: 890,
    expectedYear: 2025,
    type: '재개발', status: '시공중',
    developer: 'DL이앤씨', brand: 'e편한세상',
    subway: '6호선 증산역 도보 3분',
    schoolZone: '가좌초·가재울중',
    riverView: false,
    highlights: ['DMC 수혜권', '6호선 역세권', '시공 중'],
    notes: '분양가 미확정.',
  },
  {
    name: '고덕강일3단지 (LH 공공분양)',
    nameShort: '고덕강일3단지',
    gu: '강동구', dong: '강일동',
    totalUnits: 2514, generalSaleUnits: 2514,
    expectedYear: 2025,
    type: '신규', status: '분양중',
    developer: '한국토지주택공사(LH)', brand: 'LH',
    subway: '5호선 고덕역 도보 12분',
    schoolZone: '강일초·강일중',
    riverView: false,
    highlights: ['공공분양', '전 세대 일반분양'],
    presalePrice: 1900, presalePriceNote: '확정',
    notes: '공공분양 확정 분양가.',
  },
  {
    name: '장위자이레디언트 (장위4구역)',
    nameShort: '장위자이',
    gu: '성북구', dong: '장위동',
    totalUnits: 2840, generalSaleUnits: 1140,
    expectedYear: 2025,
    type: '재개발', status: '시공중',
    developer: 'GS건설', brand: '자이',
    subway: '6호선 돌곶이역 도보 5분',
    schoolZone: '장위초·장위중',
    riverView: false,
    highlights: ['장위 뉴타운 최대 규모', '6호선 역세권', '시공 중'],
    notes: '분양가 미확정.',
  },
  {
    name: '신길뉴타운 (신길1구역 재개발)',
    nameShort: '신길뉴타운',
    gu: '영등포구', dong: '신길동',
    totalUnits: 2700, generalSaleUnits: 980,
    expectedYear: 2026,
    type: '재개발', status: '시공중',
    developer: '롯데건설', brand: '롯데캐슬',
    subway: '1·5호선 신길역 도보 5분',
    schoolZone: '신길초·영일중',
    riverView: false,
    highlights: ['1·5호선 더블역세권', '여의도 1정거장', '시공 중'],
    notes: '분양가 미확정.',
  },
]

// ── District-level supply breakdown (2025-2027 예정 세대수) ───
export const DISTRICT_SUPPLY_2025_2027: Record<string, number> = {
  '강남구': 5200, '서초구': 4800, '강동구': 6300, '송파구': 3900,
  '마포구': 2100, '용산구': 1900, '서대문구': 2800, '성북구': 3100,
  '동작구': 1900, '영등포구': 2800, '강서구': 1800, '노원구': 1200,
  '은평구': 1500, '양천구': 1100, '관악구': 900,
}
